# Generated by Django 3.2.16 on 2022-12-23 10:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookcases', '0002_alter_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='book_preview', max_length=255, verbose_name='image'),
        ),
    ]
