# Generated by Django 3.2.16 on 2022-12-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcases', '0003_alter_book_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='excerpt',
            field=models.TextField(max_length=50),
        ),
    ]
