# Generated by Django 3.2.16 on 2022-12-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookcases', '0005_auto_20221225_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcase_book',
            old_name='book_id',
            new_name='book',
        ),
    ]
