# Generated by Django 3.2.16 on 2023-01-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookcases', '0007_auto_20230105_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcase_book',
            options={'ordering': ['-added_on']},
        ),
        migrations.RemoveField(
            model_name='bookcase_book',
            name='updated_on',
        ),
    ]
